name: gtd_booking
description: A new Flutter module project.
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=3.2.0"

dependencies:
  flutter:
    sdk: flutter

  gtd_utils:
    path: ../GtdUtils
  # vib_resource:
  #   path: ../resources/vib_resource
  gotadi_resource:
    path: ../resources/gotadi_resource
  resource:
    path: ../resources/resource
  common_resource:
    path: ../resources/common_resource
  # resource:
  #   path: ../../dependencies/resource
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # flutter_riverpod: ^2.1.3
  go_router: ^13.2.0
  path_provider: ^2.0.14
  url_launcher: ^6.1.8
  hive: ^2.2.3
  intl: any
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.1
  provider: ^6.0.5
  flutter_easyloading: ^3.0.5
  flutter_bloc: ^8.1.3
  collection: any
  equatable: ^2.0.5
  uuid: ^4.3.3
  http: any
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1

  flutter_datetime_picker: ^1.5.1
  rxdart: ^0.27.7
  loadmore: ^2.0.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # assets:
  # - lib/resource/gotadi_invoice_term.html
  # - packages/resource/assets/images/
  # - packages/resource/assets/images/demo/
  # - packages/resource/assets/icons/
  # - packages/resource/assets/icons/flight/
  # - packages/resource/assets/icons/airlines/
  # - packages/resource/vib_assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: packages/vib_resource/assets/fonts/Inter/Inter-Black.ttf
  #       - asset: packages/vib_resource/assets/fonts/Inter/Inter-Bold.ttf
  #       - asset: packages/vib_resource/assets/fonts/Inter/Inter-ExtraBold.ttf
  #       - asset: packages/vib_resource/assets/fonts/Inter/Inter-ExtraLight.ttf
  #       - asset: packages/vib_resource/assets/fonts/Inter/Inter-Light.ttf
  #       - asset: packages/vib_resource/assets/fonts/Inter/Inter-Medium.ttf
  #       - asset: packages/vib_resource/assets/fonts/Inter/Inter-Regular.ttf
  #       - asset: packages/vib_resource/assets/fonts/Inter/Inter-SemiBold.ttf
  #       - asset: packages/vib_resource/assets/fonts/Inter/Inter-Thin.ttf

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    android.enableJetifier: true
    androidPackage: com.gtd.gtdBooking
    iosBundleIdentifier: com.gtd.gtdBooking
