name: gtd_utils
description: A new Flutter module project.
publish_to: "none"
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # vib_resource:
  #   path: ../resources/vib_resource
  # vib_resource:
  #   path: ../resources/vib_resource
  common_resource:
    path: ../resources/common_resource

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: any
  go_router: ^13.2.0
  hive: any
  shared_preferences: ^2.1.1
  # path_provider: ^2.0.14
  syncfusion_flutter_datepicker: ^24.2.7
  easy_localization: ^3.0.1
  flutter_localizations:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_bloc: ^8.1.3
  collection: any
  rxdart: ^0.27.7
  equatable: ^2.0.5
  crypto: ^3.0.2
  async:
  # Dependencies for Repositories
  # freezed: ^2.3.2
  dio: ^5.4.1
  shimmer: ^3.0.0
  flutter_dotenv: ^5.0.2
  azlistview: any
  path_drawing: any
  path: ^1.8.3
  flutter_html: any
  webview_flutter: ^4.2.2
  url_launcher: ^6.1.12
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  lottie: ^3.1.0
  reactive_forms: ^16.1.1
  in_app_review: ^2.0.8
  map_launcher: ^3.0.1
  just_the_tooltip: ^0.0.12
  smooth_page_indicator: ^1.1.0
  photo_view: ^0.14.0
  sticky_headers: "^0.3.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: any
  build_runner: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  # - packages/resource/assets/images/
  # - packages/resource/assets/images/demo/
  # - packages/resource/assets/icons/
  # - packages/resource/assets/icons/flight/
  # - packages/resource/assets/icons/airlines/
  # - packages/resource/vib_assets/translations/
  assets:
    - lib/data/resource/gotadi_data/gotadi_invoice_term.html
    - lib/data/resource/gotadi_data/gotadi_about.html
  #   - packages/resource/
  # - assets/icons/
  # - assets/icons/flight/
  #   - images/a_dot_ham.jpeg
  # assets:
  #   - assets/env/
  #   - .env
  #   - assets/env/.env.uat
  #   - assets/env/.env.prod

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter/Inter-Black.ttf
  #       - asset: assets/fonts/Inter/Inter-Bold.ttf
  #       - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
  #       - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
  #       - asset: assets/fonts/Inter/Inter-Light.ttf
  #       - asset: assets/fonts/Inter/Inter-Medium.ttf
  #       - asset: assets/fonts/Inter/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter/Inter-SemiBold.ttf
  #       - asset: assets/fonts/Inter/Inter-Thin.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.gtd.utils
    iosBundleIdentifier: com.gtd.utils
